AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SourceDataBucketNamePrefix:
    Default: 'ee-assets-prod-'
    Description: Source data bucket name prefix
    Type: String

  SourceModuleVersionPrefix:
    Default: 'modules/cfdd4f678e99415a9c1f11342a3a9887/v1/'
    Description: Source module version prefix
    Type: String

  SisDemoMockDataPrefix:
    Default: 'mockdata/sis_demo/'
    Description: SIS Demo source data prefix
    Type: String

  LmsDemoMockDataPrefix:
    Default: 'mockdata/lms_demo/v1/'
    Description: LMS Demo source data prefix
    Type: String

  RawDataBucketName:
    Default: 'data-edu-raw-6114e92354234c16b7d90ca97ccc8fc6'
    Description: Raw data bucket name
    Type: String

  SisDemoRawDataPrefix:
    Default: 'sis_demo/'
    Description: SIS Demo raw data prefix
    Type: String

  LmsDemoRawDataPrefix:
    Default: 'lms_demo/'
    Description: LMS Demo raw data prefix
    Type: String

  SourceCodeBucketNamePrefix:
    Default: 'ee-assets-prod-6114e92354234c16b7d90ca97ccc8fc6-'
    Description: Source data bucket name prefix
    Type: String

Resources:
  DataEduFetchDemoDataLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: '2012-10-17'
      RoleName: data-edu-fetch-demo-data-lambda-role
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  DataEduFetchDemoDataLambdaRoleDefaultPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action: 
              - 's3:ListBucket'
            Effect: Allow
            Resource: 
              - !Sub arn:aws:s3:::${RawDataBucketName}
          - Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${RawDataBucketName}/*
          - Action:
              - 'logs:CreateLogGroup'
            Effect: Allow
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Action:
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Effect: Allow
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
        Version: '2012-10-17'
      PolicyName: data-edu-fetch-demo-data-lambda-role-default-policy
      Roles:
        - Ref: DataEduFetchDemoDataLambdaRole

  DataEduFetchDemoDataLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket:
          'Fn::Join':
            - ''
            - - Ref: SourceCodeBucketNamePrefix
              - Ref: 'AWS::Region'
        S3Key:
          'Fn::Join':
            - ''
            - - Ref: SourceModuleVersionPrefix
              - 'lambda/'
              - 'data_edu_fetch_demo_data.zip'
      Role:
        'Fn::GetAtt':
          - DataEduFetchDemoDataLambdaRole
          - Arn
      Description: >-
        Lambda function that fetches demo data from source data bucket and
        copies the data objects to raw data bucket.
      FunctionName: data-edu-fetch-demo-data
      Handler: data_edu_fetch_demo_data.lambda_handler
      MemorySize: 256
      Runtime: python3.7
      Timeout: 600
      Environment:
        Variables:
          SOURCE_DATA_BUCKET_NAME_PREFIX:
            Ref: SourceDataBucketNamePrefix
          SOURCE_MODULE_VERSION_PREFIX:
            Ref: SourceModuleVersionPrefix
          SIS_DEMO_MOCK_DATA_PREFIX:
            Ref: SisDemoMockDataPrefix
          LMS_DEMO_MOCK_DATA_PREFIX:
            Ref: LmsDemoMockDataPrefix
          RAW_DATA_BUCKET_NAME:
            Ref: RawDataBucketName
          SIS_DEMO_RAW_DATA_PREFIX:
            Ref: SisDemoRawDataPrefix
          LMS_DEMO_RAW_DATA_PREFIX:
            Ref: LmsDemoRawDataPrefix
    DependsOn:
      - DataEduFetchDemoDataLambdaRoleDefaultPolicy
      - DataEduFetchDemoDataLambdaRole

